### ISSUE TITLE
build fail. Message like that： Required: EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

### ISSUE THREAD

**Issue by gybin02** [nekocode/JarFilterPlugin#1]
Required: EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

My Android  Studio is  3.1.1

 And 

  classpath 'com.android.tools.build:gradle:3.1.1'

**Comment by gybin02** [comment]
you can fix this:
https://blog.csdn.net/fengrui_sd/article/details/78658103

**Comment by nekocode** [comment]
Thanks for the report. I will fix it soon.

**Comment by nekocode** [comment]
I can't reproduce this error.
Are you using this plugin in android library module? In fact, it can only be used in application module.

Or, you can also try the new version 1.2

**Comment by gybin02** [comment]
I used  in application module. I will try new Version 2.0 today.

**Comment by gybin02** [comment]
still has the problem：
log : 



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarFilterForDebug'.
> Unexpected scopes found in folder '/Users/tony/Documents/github/OKHttpSample/app/build/intermediates/transforms/AspectTransform/debug'. Required: EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS


MY code: 
Project Level   build.gradle

>   dependencies {
        classpath 'com.android.tools.build:gradle:3.1.1'
        classpath "com.github.nekocode:JarFilterPlugin:2.0"


Application Level


>  apply plugin: 'jar-filter'
jarFilters {
    "com.android.support:appcompat-v7:(.*)" {
        excludes = [
                'android/support/v7/app/AppCompatActivity.class',
                'android/support/v7/app/AppCompatActivity\\$(.*).class'
        ]
    }
}



The Problem Is  this plugin  not  compatibility with Gradle 3.0+

**Comment by nekocode** [comment]
This folder `xxx/transforms/AspectTransform/debug` is not used by JarFilterPlugin. It seems that the problem isn't caused by JarFilterPlugin.

**Comment by gybin02** [comment]
Execution failed for task ':app:transformClassesWithJarFilterForDebug'.


So this plugin is not  compatibility with 'android-aspectjx'

> apply plugin: 'android-aspectjx'

> dependencies {
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:1.0.10'
}

**Comment by nekocode** [comment]
Try putting `apply plugin: 'jar-filter'` in front of `apply plugin: 'android-aspectjx'`.

**Comment by nekocode** [comment]
Or try to update your `android-aspectjx` plugin:
https://github.com/JustKiddingBaby/FragmentRigger/issues/4

**Comment by gybin02** [comment]
Try putting apply plugin: 'jar-filter' in front of apply plugin: 'android-aspectjx'.


=== Great, work for me.
