### ISSUE TITLE
内部类的属性，方法怎么改？

### ISSUE THREAD

**Issue by JakeWoki** [nekocode/JarFilterPlugin#5]

**Comment by nekocode** [comment]
具体看这里: https://juejin.cn/post/6844903597591756807
可以替换相关类的源码

**Comment by JakeWoki** [comment]
![微信截图_20210601102756](https://user-images.githubusercontent.com/6948411/120258145-12d10980-c2c4-11eb-896c-fa219262e483.png)
内部属性编译通不过

**Comment by nekocode** [comment]
1. 要么使用反射来访问内部属性
2. 要么将 Respone 类也一起替换了

**Comment by JakeWoki** [comment]
好的感谢
